-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 14:26:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ghettobasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ghettobasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ghettobasa` DEFAULT CHARACTER SET utf8 ;
USE `ghettobasa` ;

-- -----------------------------------------------------
-- Table `ghettobasa`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Users` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `nationalId` VARCHAR(45) NOT NULL,
  `userId` VARCHAR(45) NOT NULL,
  `birthDate` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `phonenumber` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `biography` VARCHAR(100) NULL DEFAULT 'none',
  `photoUrl` VARCHAR(100) NULL,
  `street` VARCHAR(45) NULL,
  `suburb` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `proofOfResidenceUrl` VARCHAR(100) NULL DEFAULT 'none',
  `nationalIdPhotoUrl` VARCHAR(100) NULL DEFAULT 'none',
  `skills` VARCHAR(100) NULL DEFAULT 'none',
  `status` VARCHAR(45) NULL,
  `deleted` VARCHAR(50) NULL DEFAULT 'false',
  `userType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `nationalId_UNIQUE` (`nationalId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ghettobasa`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Jobs` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`Jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobId` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `suburb` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `dateposted` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `amount` DECIMAL(20) NULL,
  `negotiable` VARCHAR(45) NULL,
  `expiringDate` VARCHAR(45) NULL,
  `requiredSkills` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  `successfulBidder` VARCHAR(45) NULL,
  `userId` VARCHAR(45) NULL,
  `renewed` VARCHAR(45) NULL DEFAULT 'false',
  `deleted` VARCHAR(45) NULL DEFAULT 'false',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `jobId_UNIQUE` (`jobId` ASC) VISIBLE,
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  INDEX `bidder_idx` (`successfulBidder` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bidder`
    FOREIGN KEY (`successfulBidder`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ghettobasa`.`JobBids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`JobBids` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`JobBids` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobId` VARCHAR(45) NULL,
  `bidderId` VARCHAR(45) NULL,
  `bidDate` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `bidderName` VARCHAR(45) NULL,
  `bidderPhotoUrl` VARCHAR(45) NULL,
  `deleted` VARCHAR(45) NULL DEFAULT 'false',
  PRIMARY KEY (`id`),
  INDEX `jobId_idx` (`jobId` ASC) VISIBLE,
  INDEX `bidder_idx` (`bidderId` ASC) VISIBLE,
  CONSTRAINT `jobId`
    FOREIGN KEY (`jobId`)
    REFERENCES `ghettobasa`.`Jobs` (`jobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bidder`
    FOREIGN KEY (`bidderId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ghettobasa`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Ratings` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`Ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NULL,
  `rating` INT NULL,
  `dateRated` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`userId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ghettobasa`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NULL,
  `review` VARCHAR(200) NULL,
  `dateReviewed` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`userId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ghettobasa`.`SystemUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`SystemUsers` ;

CREATE TABLE IF NOT EXISTS `ghettobasa`.`SystemUsers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userType` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL,
  `hash` VARCHAR(200) NULL,
  `deleted` VARCHAR(45) NULL DEFAULT 'false',
  `userId` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user\_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `user\`
    FOREIGN KEY (`userId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
