-- MySQL Script generated by MySQL Workbench
-- Fri Jan  8 09:49:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ghettobasa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ghettobasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ghettobasa` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ghettobasa` ;

-- -----------------------------------------------------
-- Table `ghettobasa`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `nationalId` VARCHAR(45) NOT NULL,
  `userId` VARCHAR(45) NOT NULL,
  `birthDate` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `phonenumber` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `biography` VARCHAR(100) NULL DEFAULT 'none',
  `photoUrl` VARCHAR(100) NULL,
  `street` VARCHAR(45) NULL,
  `suburb` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `proofOfResidenceUrl` VARCHAR(100) NULL DEFAULT 'none',
  `nationalIdPhotoUrl` VARCHAR(100) NULL DEFAULT 'none',
  `skills` VARCHAR(100) NULL DEFAULT 'none',
  `status` VARCHAR(45) NULL,
  `deleted` TINYINT NULL,
  `userType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `nationalId_UNIQUE` (`nationalId` ASC) ,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) )
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Jobs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`Jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobId` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `suburb` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `dateposted` DATE NULL,
  `category` VARCHAR(45) NULL,
  `amount` DECIMAL(20) NULL,
  `negotiable` TINYINT NULL,
  `expiringDate` DATE NULL,
  `requiredSkills` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  `successfulBidder` VARCHAR(45) NULL,
  `posterId` VARCHAR(45) NULL,
  `renewed` VARCHAR(45) NULL DEFAULT 'false',
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `jobId_UNIQUE` (`jobId` ASC) ,
  INDEX `userId_idx` (`posterId` ASC) ,
  INDEX `bidder_idx` (`successfulBidder` ASC) ,
  CONSTRAINT `userId`
    FOREIGN KEY (`posterId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bidder`
    FOREIGN KEY (`successfulBidder`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`JobBids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`JobBids` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`JobBids` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobRef` VARCHAR(45) NULL,
  `bidderId` VARCHAR(45) NULL,
  `bidDate` DATE NULL,
  `status` VARCHAR(45) NULL,
  `bidderName` VARCHAR(45) NULL,
  `bidderPhotoUrl` VARCHAR(45) NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobId_idx` (`jobRef` ASC) ,
  INDEX `bidder_idx` (`bidderId` ASC) ,
  CONSTRAINT `job`
    FOREIGN KEY (`jobRef`)
    REFERENCES `ghettobasa`.`Jobs` (`jobId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bidder`
    FOREIGN KEY (`bidderId`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Ratings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`Ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userRefer` VARCHAR(45) NULL,
  `rating` INT NULL,
  `dateRated` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userRefer` ASC) ,
  CONSTRAINT `user3`
    FOREIGN KEY (`userRefer`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`Reviews` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userRef` VARCHAR(45) NULL,
  `review` VARCHAR(200) NULL,
  `dateReviewed` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userRef` ASC) ,
  CONSTRAINT `user1`
    FOREIGN KEY (`userRef`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`SystemUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`SystemUsers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`SystemUsers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userType` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL,
  `hash` VARCHAR(200) NULL,
  `deleted` TINYINT NULL,
  `userRefe` VARCHAR(45) NULL,
  `resetRequest` VARCHAR(200) NULL DEFAULT 'none',
  PRIMARY KEY (`id`),
  INDEX `user\_idx` (`userRefe` ASC) ,
  CONSTRAINT `user2`
    FOREIGN KEY (`userRefe`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ghettobasa`.`AuditTrail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ghettobasa`.`AuditTrail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ghettobasa`.`AuditTrail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userRefere` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `date` DATE NULL,
  `action` VARCHAR(100) NULL,
  `service` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userRefere` ASC) ,
  CONSTRAINT `user3`
    FOREIGN KEY (`userRefere`)
    REFERENCES `ghettobasa`.`Users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
